version: "3.5"
services:
  m3db_seed:
    networks:
      - backend
    image: quay.io/m3db/m3dbnode:latest
    volumes:
      - "./config/m3/m3dbnode.yml:/etc/m3dbnode/m3dbnode.yml"
      - "./config/m3/schema.proto:/etc/m3dbnode/schema.proto"
    environment:
      - M3DB_HOST_ID=m3db_seed
    expose:
      - "2379"
      - "9002"
      - "9003"
      - "9004"
    ports:
      - "0.0.0.0:2379:2379"
      - "0.0.0.0:9002:9002"
      - "0.0.0.0:9003:9003"
      - "0.0.0.0:9004:9004"
    privileged: true
    cap_add:
      - ALL
  m3coordinator:
    expose:
      - "7201"
      - "7203"
      - "7204"
      - "7507"
    ports:
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:7203:7203"
      - "0.0.0.0:7204:7204"
      - "0.0.0.0:7507:7507"
    networks:
      - backend
    image: quay.io/m3db/m3coordinator:latest
    volumes:
      - "./config/m3/m3coordinator.yml:/etc/m3coordinator/m3coordinator.yml"
      - "./config/m3/schema.proto:/etc/m3coordinator/schema.proto"
    depends_on:
      - "m3db_seed"
  m3query:
    expose:
      - "7201"
      - "7203"
      - "7204"
      - "7507"
    ports:
      - "0.0.0.0:7221:7201"
      - "0.0.0.0:7223:7203"
      - "0.0.0.0:7224:7204"
      - "0.0.0.0:7527:7507"
    networks:
      - backend
    image: quay.io/m3db/m3query:latest
    volumes:
      - "./config/m3/m3query.yml:/etc/m3query/m3query.yml"
    depends_on:
      - "provisioner"
  prometheus:
    expose:
      - "9090"
    ports:
      - "0.0.0.0:9090:9090"
    networks:
      - backend
    image: prom/prometheus:latest
    volumes:
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - "provisioner"
  provisioner:
    environment:
      - USE_MULTI_DB_NODES=false
      - USE_MULTI_PROMETHEUS_NODES=false
    networks:
      - backend
    image: dwdraju/alpine-curl-jq:latest
    depends_on:
      - "m3db_seed"
    volumes:
      - "./bin/provision.sh:/tmp/provision.sh"
    entrypoint: /tmp/provision.sh
  grafana:
    expose:
      - "3000"
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - backend
    image: grafana/grafana:latest
    volumes:
      - "./config/grafana/provisioning/:/etc/grafana/provisioning/"
      - "./config/grafana/dashboards/:/var/lib/grafana/dashboards/"
    environment:
      - GF_LOG_LEVEL=error
    depends_on:
      - "provisioner"
  fluentbit:
    expose:
      - "2021"
    ports:
      - "0.0.0.0:2021:2021"
    networks:
      - backend
    image: fluent/fluent-bit:1.8
    volumes:
      - "./config/fluentbit/:/fluent-bit/etc/"
    depends_on:
      - "provisioner"
networks:
  backend:
