{
 "title": "M3DB Node Details",
 "description": "This dashboard visualizes much of the important information about an M3DB node's current status, health, performance, and load. It is very useful for monitoring M3DB clusters.",
 "tags": [ "disable-sync" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PoolType",
    "query": "series_pool,block_pool,encoder_pool,context_pool,iterator_pool,multi_iterator_pool,segment_reader_pool,bytes_pool,fetch_block_metadata_results_pool,fetch_blocks_metadata_results_pool,block_metadata_pool,block_metadata_slice_pool,blocks_metadata_pool,blocks_metadata_slice_pool,host_block_metadata_slice_pool,identifier_pool"
   },
   { "name": "step", "label": "step", "query": "30s,1m,5m,10m" },
   { "name": "instance", "label": "instance", "query": ".*" },
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Bootstrap Node Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bootstrapped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(database_bootstrapped{instance=~\"$instance\"} == bool 1)"
    }
   ]
  },
  {
   "title": "Bootstrapping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(database_bootstrapped{instance=~\"$instance\"} == bool 0)"
    }
   ]
  },
  {
   "title": "# Revisions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(build_information{instance=~\"$instance\"}) by (revision)"
    }
   ]
  },
  {
   "title": "# Runtime Versions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(build_information{instance=~\"$instance\"}) by (go_version)"
    }
   ]
  },
  { "title": "Commitlog / Inserts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Commit Log Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "commitlog_writes_queued{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Commit Log Writes / Second (Includes replication)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(rate(commitlog_writes_success{instance=~\"$instance\"}[$step]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "New Series Inserts / Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dbshard_insert_queue_inserts{instance=~\"$instance\"}[$step])) by (pending_write)",
     "legendFormat": "pendingWrite-{{pending_write}}"
    }
   ]
  },
  {
   "title": "Un-Tagged RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Reads / Writes / Minute",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(service_fetchBatchRaw_success{instance=~\"$instance\"}[1m])"
      },
      {
       "expr": "rate(service_fetchBatchRaw_errors{instance=~\"$instance\"}[1m])"
      },
      {
       "expr": "rate(service_writeBatchRaw_success{instance=~\"$instance\"}[1m])"
      },
      {
       "expr": "rate(service_writeBatchRaw_errors{instance=~\"$instance\"}[1m])"
      }
     ]
    },
    {
     "title": "Server Side Write Latency (p99)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "service_writeBatchRaw_latency{instance=~\"$instance\",quantile=\"0.99\"}"
      }
     ]
    },
    {
     "title": "Server Side Fetch Latency (p99)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "service_fetchBatchRaw_latency{instance=~\"$instance\",quantile=\"0.99\"}"
      }
     ]
    }
   ]
  },
  { "title": "Tagged RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Service Reads / Writes / Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(service_writeTaggedBatchRaw_success{instance=~\"$instance\"}[$step]))",
     "legendFormat": "writeTaggedSuccess"
    },
    {
     "expr": "sum(rate(service_writeTaggedBatchRaw_errors{instance=~\"$instance\"}[$step]))",
     "legendFormat": "writeTaggedErrors"
    },
    {
     "expr": "sum(rate(service_fetchTaggedBatchRaw_success{instance=~\"$instance\"}[$step]))",
     "legendFormat": "fetchTaggedSuccess"
    },
    {
     "expr": "sum(rate(service_fetchTaggedBatchRaw_errors{instance=~\"$instance\"}[$step]))",
     "legendFormat": "fetchTaggedErrors"
    }
   ]
  },
  {
   "title": "Server Side Write Latency (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "service_writeTaggedBatchRaw_latency{instance=~\"$instance\",quantile=\"0.99\"}"
    }
   ]
  },
  {
   "title": "Server Side Fetch Latency (p99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "service_fetchTagged_success_latency{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU and Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Process CPU Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$step])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Utilization - Resident",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident-{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Free Space - Not Implemented",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {}
   ]
  },
  {
   "title": "Num File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Num Go Routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "runtime_num_goroutines{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Background Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bootstrapped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "database_bootstrapped{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tick Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "database_tick_duration{instance=~\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ticking",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(database_tick_active_series{instance=~\"$instance\"})",
       "legendFormat": "totalActiveSeries"
      }
     ]
    },
    {
     "title": "Flushing",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "database_fs_flush{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Snapshotting",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "database_fs_snapshot{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Index Flushing",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "database_fs_index_flush{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wired & Unwired Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wired and Unwired Blocks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "database_tick_wired_blocks{instance=~\"$instance\"}",
       "legendFormat": "wiredBlocks-{{instance}}"
      },
      {
       "expr": "database_tick_unwired_blocks{instance=~\"$instance\"}",
       "legendFormat": "unwiredBlocks-{{instance}}"
      },
      {
       "expr": "database_tick_active_blocks{instance=~\"$instance\"}",
       "legendFormat": "activeBlocks-{{instance}}"
      },
      {
       "expr": "database_tick_open_blocks{instance=~\"$instance\"}",
       "legendFormat": "openBlocks-{{instance}}"
      }
     ]
    },
    {
     "title": "Made Wired/Unwired & Merged Out of Order Blocks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(database_tick_made_expired_blocks{instance=~\"$instance\"}[$step])",
       "legendFormat": "madeExpiredBlocks-{{instance}}"
      },
      {
       "expr": "rate(database_tick_made_unwired_blocks{instance=~\"$instance\"}[$step])",
       "legendFormat": "madeUnwiredBlocks-{{instance}}"
      },
      {
       "expr": "rate(database_tick_merged_out_of_order_blocks{instance=~\"$instance\"}[$step])",
       "legendFormat": "mergedOutOfOrderBlocks-{{instance}}"
      },
      {
       "expr": "rate(database_tick_made_wired_blocks{instance=~\"$instance\"}[$step])",
       "legendFormat": "madeWiredBlocks-{{instance}}"
      }
     ]
    },
    {
     "title": "New Encoder Created / Second",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(database_series_encoder_created{instance=~\"$instance\"}[$step])",
       "legendFormat": "seriesEncoderCreated-{{instance}}"
      }
     ]
    },
    {
     "title": "Shard State",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cluster_shards_available{instace=~\"$instance\"})",
       "legendFormat": "available"
      },
      {
       "expr": "sum(cluster_shards_initializing{instace=~\"$instance\"})",
       "legendFormat": "initializing"
      },
      {
       "expr": "sum(cluster_shards_leaving{instace=~\"$instance\"})",
       "legendFormat": "leaving"
      }
     ]
    },
    {
     "title": "Wired List Capacity / Size / Evictions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "wired_list_limit{instance=~\"$instance\"}"
      },
      {
       "expr": "rate(wired_list_evicted{instance=~\"$instance\"}[$step])"
      },
      {
       "expr": "wired_list_unwireable{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Time spent in Wired List - P99",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "wired_list_evicted_after_duration{instance=~\"$instance\",quantile=\"0.99\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network In/Out - Not Implemented",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network In",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {}
     ]
    },
    {
     "title": "Network Out",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Writes / Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(database_write_tagged_success{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_tagged_success"
      },
      {
       "expr": "sum(rate(database_write_tagged_errors{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_tagged_errors"
      },
      {
       "expr": "sum(rate(database_write_success{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_success"
      },
      {
       "expr": "sum(rate(database_write_errors{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_errors"
      }
     ]
    },
    {
     "title": "Reads / Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(database_read_tagged_success{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_tagged_success"
      },
      {
       "expr": "sum(rate(database_read_tagged_errors{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_tagged_errors"
      },
      {
       "expr": "sum(rate(database_read_success{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_success"
      },
      {
       "expr": "sum(rate(database_reads_errors{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_errors"
      }
     ]
    },
    {
     "title": "QueryIDs / Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(database_queryIDs_success{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_query_ids_success"
      }
     ]
    },
    {
     "title": "Flush",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(database_flush_success{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_flush_success"
      },
      {
       "expr": "sum(increase(database_flush_errors{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_flush_errors"
      }
     ]
    },
    {
     "title": "IndexFlush",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(database_index_flush_success{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_index_flush_success"
      },
      {
       "expr": "sum(increase(database_index_flush_errors{instance=~\"$instance\"}[$step])) by (namespace)",
       "legendFormat": "{{namespace}}_index_flush_errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Peers Bootstrapping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch Shard Blocks In Progress",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3dbclient_stream_from_peers_fetch_blocks_inprogress{instace=~\"$instance\"}",
       "legendFormat": "fetchBlocksInProgress-{{instance}}"
      }
     ]
    },
    {
     "title": "Fetch Shard Blocks Metadata In Progress",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3dbclient_stream_from_peers_fetch_metadata_peers_inprogress{instace=~\"$instance\"}",
       "legendFormat": "fetchBlocksMetadataInProgress-{{instance}}"
      }
     ]
    },
    {
     "title": "Fetch Shard Blocks Enqueue Channel Length",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "m3dbclient_stream_from_peers_fetch_blocks_enqueue_channel_length{instance=~\"$instance\"}",
       "legendFormat": "fetchBlocksEnqueueChannelLength-{{instance}}"
      }
     ]
    },
    {
     "title": "Fetch Shard Blocks Metadata Batch Calls / Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3dbclient_stream_from_peers_fetch_metadata_peers_batch_call{instance=~\"$instance\"}[$step])) by (instance)",
       "legendFormat": "fetchBlocksMetadataBatchCalls-{{instance}}"
      }
     ]
    },
    {
     "title": "Fetch Shard Blocks Metadata Received / Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3dbclient_stream_from_peers_fetch_metadata_peers_received{instance=~\"$instance\"}[$step])) by (host)",
       "legendFormat": "fetchBlocksMetadataReceived-{{instance}}"
      }
     ]
    },
    {
     "title": "Fetch Shard Blocks Metadata Pagination Retry / Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3dbclient_stream_from_peers_fetch_metadata_peers_peer_retry{instance=~\"$instance\"}[$step])) by (instance)",
       "legendFormat": "fetchBlocksMetadataPaginationRetry-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Overload/Persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overloaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(service_overload_rejected{instance=~\"$instance\"}[$step])"
      }
     ]
    },
    {
     "title": "Persistence",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "database_fs_persist_write_duration_ms{instance=~\"$instance\"}"
      },
      {
       "expr": "database_fs_persist_throttle_duration_ms{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fetch Blocks Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch Block Success/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3dbclient_stream_from_peers_fetch_block_success{instance=~\"$instance\"}[$step])) by (instance)",
       "legendFormat": "fetchBlockSuccess-{{instance}}"
      }
     ]
    },
    {
     "title": "Fetch Block Error/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3dbclient_stream_from_peers_fetch_block_error{instance=~\"$instance\"}[$step])) by (instance)",
       "legendFormat": "fetchBlockError-{{instance}}"
      }
     ]
    },
    {
     "title": "Fetch Block Full-Retry/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3dbclient_stream_from_peers_fetch_block_full_retry{instance=~\"$instance\"}[$step])) by (instance)",
       "legendFormat": "fetchBlockFullRetry-{{instance}}"
      }
     ]
    },
    {
     "title": "Fetch Block Final Error/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(m3dbclient_stream_from_peers_fetch_block_final_error{instance=~\"$instance\"}[$step])) by (instance)",
       "legendFormat": "fetchBlockFinalError-{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pooling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free &  Put On Full",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "[[PoolType]]_free{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "% Pool Used - Not Implemented",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {}
     ]
    }
   ]
  },
  {
   "title": "Build Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Runtime Version",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(build_information{}) by (go_version)",
       "legendFormat": "{{go_version}}"
      }
     ]
    },
    {
     "title": "Git Revision",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(build_information{}) by (revision)",
       "legendFormat": "{{revision}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dbindex_insert_queue_index_queue_num_pending{instance=~\"$instance\"}[$step])"
      },
      {
       "expr": "rate(dbindex_index_error{instance=~\"$instance\"}[$step])"
      }
     ]
    },
    {
     "title": "Indexing End-to-End Latency - P99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "dbindex_insert_end_to_end_latency{instance=~\"$instance\",quantile=\"0.99\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Num Docs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "database_tick_index_num_docs{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Num Segments",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "database_tick_index_num_segments{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Num Compactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "dbindex_num_active_compactions{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Compaction Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "dbindex_compaction_latency{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Evicted/Sealed blocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(database_tick_index_num_blocks_evicted{instance=~\"$instance\"}[$step])"
      },
      {
       "expr": "increase(database_tick_index_num_blocks_sealed{instance=~\"$instance\"}[$step])"
      }
     ]
    }
   ]
  }
 ]
}