global:
  external_labels:
    role: "remote"
  scrape_interval:     10s
  evaluation_interval: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus01:9090', 'prometheus02:9090']

  - job_name: 'm3coordinator'
    static_configs:
      - targets:
          - m3coordinator01:7210

  - job_name: 'm3query'
    static_configs:
      - targets:
          - m3query01:7211

  - job_name: 'm3db'
    static_configs:
      - targets: ['m3db_seed:9004', 'm3db_data01:9004', 'm3db_data02:9004']

remote_read:
  - url: http://m3coordinator01:7201/api/v1/prom/remote/read
    read_recent: true

remote_write:
  - url: http://m3coordinator01:7201/api/v1/prom/remote/write
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_shards: 10
      min_shards: 3
      max_samples_per_send: 5000
      batch_send_deadline: 1m
      min_backoff: 50ms
      max_backoff: 1s
