global:
  external_labels:
    role: "remote"
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - prometheus:9090

  - job_name: 'fluentbit'
    static_configs:
      - targets:
          - fluentbit:2021

#remote_read:
#  - url: http://m3coordinator:7201/api/v1/prom/remote/read
#    read_recent: true

#remote_write:
#  - url: http://m3coordinator:7201/api/v1/prom/remote/write
#    remote_timeout: 30s
#    queue_config:
#      capacity: 10000
#      max_shards: 10
#      min_shards: 3
#      max_samples_per_send: 5000
#      batch_send_deadline: 1m
#      min_backoff: 50ms
#      max_backoff: 1s
