apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus01:9090/
  access: proxy
  isDefault: true
  jsonData:
    httpMethod: POST
- name: M3Query
  type: prometheus
  url: http://m3query01:7201
  access: proxy
  isDefault: false
  jsonData:
    httpMethod: POST
